version: '3'
services:
  mysqldb:
    image: ramadepo/rsmysql:1.5
    build:
      context: ./mysql
      dockerfile: Dockerfile
    networks:
      - my-net
  my-rs:
    image: ramadepo/restaurant-shuffle:1.5
    build:
      context: ./restaurantshuffle
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    ports:
      - "5000:5000"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge