version: '3'
services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpassword
      - MYSQL_DATABASE=db_flask_rs
    networks:
      - my-net
  my-rs:
    image: ramadepo/restaurant-shuffle:1.4
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    ports:
      - "5000:5000"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge