"""empty message

Revision ID: 9f51b8570a9e
Revises: 8ab3fa06653d
Create Date: 2019-06-16 11:28:33.529728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f51b8570a9e'
down_revision = '8ab3fa06653d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('UC_Shop', 'shop', ['name', 'region_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('UC_Shop', 'shop', type_='unique')
    # ### end Alembic commands ###
